# Generated by Django 6.0.3 on 2026-09-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_accesstokenblacklist_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessTokenBlacklist',
        ),
    ]
