# Generated by Django 6.0.3 on 2026-03-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30, verbose_name='書籍名稱')),
                ('description', models.CharField(max_length=255, verbose_name='書籍描述')),
                ('writer', models.CharField(max_length=30, verbose_name='作者')),
                ('publish_date', models.DateField(verbose_name='出版日期')),
            ],
            options={
                'verbose_name': '書本',
                'verbose_name_plural': '書本',
            },
        ),
    ]
