# Generated by Django 6.0.3 on 2026-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='建立時間'),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='修改時間'),
        ),
    ]
