"""
Django settings for project_crud_example project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import sys
from datetime import datetime, timedelta
from pathlib import Path

from colorlog import ColoredFormatter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%3&9$7#+0nj6tqxiz7(3=#gsgfq&+eqdhd-og$1p0bqnrnn=n="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "app.book",
    "app.user",
]

MIDDLEWARE = [
    # 放在最前面（request 最先經過、response 最後經過），
    # 讓其後所有 middleware / View / Service 的 log 都能帶到 trace_id
    "core.middleware.trace_id.TraceIDMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.response_format.CustomResponseMiddleware",
]

ROOT_URLCONF = "project_crud_example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project_crud_example.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# 指定自訂的 User Model
AUTH_USER_MODEL = "user.CustomUser"

# DRF 預設使用 JWT 驗證
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "app.user.authentication.BlacklistJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # drf-spectacular：產生 OpenAPI schema
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # 全域分頁：list 類 API 一律使用自訂的 StandardPageNumberPagination
    # （允許 client 用 ?page_size= 覆寫每頁筆數，上限 100）
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardPageNumberPagination",
    # 全域例外處理：統一錯誤回應格式並接住 django.core.exceptions
    "EXCEPTION_HANDLER": "core.exception.exception_handler.custom_exception_handler",
}

# drf-spectacular 設定
SPECTACULAR_SETTINGS = {
    "TITLE": "CRUD Example API",
    "DESCRIPTION": "Django + DRF + SimpleJWT CRUD 教學範例 API 文件。",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# =============================================================================
# Logging
# =============================================================================
# 採 Django 標準的 dictConfig 設定（settings.LOGGING），程式碼端一律使用
# `logger = logging.getLogger(__name__)`，不自製 log wrapper。
#
# 設計重點：
#   1. trace_id  ：由 TraceIDMiddleware + TraceIDFilter 注入，串起同一次 request 的所有 log。
#   2. 日期分檔  ：logs/<YYYY-MM-DD>/ 目錄，搭配 TimedRotatingFileHandler 每日午夜換檔、保留 30 天。
#   3. 彩色輸出  ：console 用 colorlog 依等級上色；落檔用純文字，避免 ANSI 控制碼污染檔案。
#   4. 分流      ：console 只收 INFO+（畫面乾淨），檔案收 DEBUG+（完整可追查）；
#                  ERROR+ 另外複寫一份 error.log，出事時不必在 system.log 大海撈針。

# 依「當天日期」建立 log 目錄；伺服器啟動時決定一次即可
LOG_DIR = BASE_DIR / "logs" / datetime.now().strftime("%Y-%m-%d")
LOG_DIR.mkdir(parents=True, exist_ok=True)

# %(trace_id)s 不是 logging 內建欄位，靠 TraceIDFilter 補上；
# 少了那個 filter 的 handler 會在格式化時噴 KeyError，故兩者必須成對出現。
LOG_FORMAT = "%(asctime)s | %(levelname)-8s | %(name)s | trace_id=%(trace_id)s | %(message)s"
COLOR_LOG_FORMAT = f"%(log_color)s{LOG_FORMAT}"
DATE_FORMAT = "%Y-%m-%d %H:%M:%S"

LOGGING = {
    "version": 1,
    # False：不關掉此設定未列出的既有 logger（例如第三方套件在 import 時建立的），
    # 讓它們仍能沿用 root handler
    "disable_existing_loggers": False,
    "filters": {
        "trace_id": {
            "()": "core.logging_filters.TraceIDFilter",
        },
    },
    "formatters": {
        # 落檔用：純文字
        "standard": {
            "format": LOG_FORMAT,
            "datefmt": DATE_FORMAT,
        },
        # console 用：依等級上色，開發時一眼看出 WARNING / ERROR
        "colored": {
            "()": ColoredFormatter,
            "format": COLOR_LOG_FORMAT,
            "datefmt": DATE_FORMAT,
            "log_colors": {
                "DEBUG": "cyan",
                "INFO": "green",
                "WARNING": "black,bg_yellow",
                "ERROR": "white,bg_red",
                "CRITICAL": "white,bg_purple",
            },
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "colored",
            "filters": ["trace_id"],
            "stream": sys.stdout,
        },
        # 系統全量 log：每天午夜換檔，保留 30 份
        "system_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "system.log",
            "when": "midnight",
            "backupCount": 30,
            "encoding": "utf-8",
            "formatter": "standard",
            "filters": ["trace_id"],
        },
        # 錯誤專用 log：只收 ERROR 以上
        "error_file": {
            "level": "ERROR",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "error.log",
            "when": "midnight",
            "backupCount": 30,
            "encoding": "utf-8",
            "formatter": "standard",
            "filters": ["trace_id"],
        },
    },
    "loggers": {
        # Django 框架本身（request 錯誤、DB backend 等）
        "django": {
            "handlers": ["console", "system_file", "error_file"],
            "level": "INFO",
            "propagate": False,
        },
        # SQL 查詢語句：需要看 SQL 時再改成 DEBUG，平時關掉避免洗版
        "django.db.backends": {
            "handlers": ["system_file"],
            "level": "INFO",
            "propagate": False,
        },
        # 本專案業務程式碼：因為 logger 名稱取自 __name__（如 app.book.services.
        # book_service），logging 的階層繼承機制會讓所有 app.* 都套用這組設定，
        # 不必逐一列出每個模組
        "app": {
            "handlers": ["console", "system_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # 共用基礎設施（middleware、例外處理等）
        "core": {
            "handlers": ["console", "system_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
    # 沒對到上面任何 logger 的訊息（第三方套件等）在此兜底
    "root": {
        "handlers": ["console", "system_file", "error_file"],
        "level": "WARNING",
    },
}

SIMPLE_JWT = {
    # Access token 有效期：15 分鐘（短暫，降低外洩風險）
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # Refresh token 有效期：7 天（換發新 access token 用）
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # 每次用 refresh token 換發時，同時輪換 refresh token（增加安全性）
    "ROTATE_REFRESH_TOKENS": True,
    # 輪換後舊的 refresh token 自動加入黑名單
    "BLACKLIST_AFTER_ROTATION": True,
}
