"""
Django settings for project_crud_example project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%3&9$7#+0nj6tqxiz7(3=#gsgfq&+eqdhd-og$1p0bqnrnn=n="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "app.book",
    "app.user",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.response_format.CustomResponseMiddleware",
]

ROOT_URLCONF = "project_crud_example.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project_crud_example.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# 指定自訂的 User Model
AUTH_USER_MODEL = "user.CustomUser"

# DRF 預設使用 JWT 驗證
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "app.user.authentication.BlacklistJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # drf-spectacular：產生 OpenAPI schema
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # 全域分頁：list 類 API 一律使用自訂的 StandardPageNumberPagination
    # （允許 client 用 ?page_size= 覆寫每頁筆數，上限 100）
    "DEFAULT_PAGINATION_CLASS": "core.pagination.StandardPageNumberPagination",
    # 全域例外處理：統一錯誤回應格式並接住 django.core.exceptions
    "EXCEPTION_HANDLER": "core.exception.exception_handler.custom_exception_handler",
}

# drf-spectacular 設定
SPECTACULAR_SETTINGS = {
    "TITLE": "CRUD Example API",
    "DESCRIPTION": "Django + DRF + SimpleJWT CRUD 教學範例 API 文件。",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

SIMPLE_JWT = {
    # Access token 有效期：15 分鐘（短暫，降低外洩風險）
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # Refresh token 有效期：7 天（換發新 access token 用）
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # 每次用 refresh token 換發時，同時輪換 refresh token（增加安全性）
    "ROTATE_REFRESH_TOKENS": True,
    # 輪換後舊的 refresh token 自動加入黑名單
    "BLACKLIST_AFTER_ROTATION": True,
}
